/**
 * @format
 */

import React from 'react'
import Head from 'next/head'

export default function Home() {
  return React.createElement('div', null,
    React.createElement(Head, null,
      React.createElement('title', null, 'Create Next App'),
      React.createElement('meta', {name: 'description', content: 'Generated by create-wizard'}),
      React.createElement('link', {rel: 'icon', href: '/favicon.ico'})
    ),
    React.createElement('main', null,
      React.createElement('h1', null,
        'Welcome to ',
        React.createElement('a', {href: 'https://nextjs.org'}, 'Next.js!')
      )
    )
  )
}
