name: CI

on:
  push:
    branches: [dev]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm test

      - name: Lint code
        run: npm run lint

      - name: Type check
        run: npm run typecheck

      - name: AI Review (Placeholder)
        run: echo "This is a placeholder for an AI code review. Replace with your AI review tool."

      - name: Build project
        run: npm run build
